### ISSUE TITLE
First Try with SolaX X3 9.0T  via RS485:   toml.decoder.TomlDecodeError: Unbalanced quotes (line 39 column 24 char 1554)

### ISSUE THREAD

**Issue by 4920441** [InfernoEmbedded/PowerScraper#19]
Oh me stupid......   Forgot **"** after ttyUSB0..........................

**Comment by 4920441** [comment]
> Hi,
> 
> don't know what the Problem is her....
> 
> ```
> ./power_scraper.py 
> WARNING:pymodbus.client.asynchronous:Importing deprecated clients. Dependency Twisted is Installed
> Traceback (most recent call last):
>   File "/home/ug/PowerScraper/./power_scraper.py", line 78, in <module>
>     config = toml.loads(conffile.read())
>   File "/usr/local/lib/python3.9/dist-packages/toml/decoder.py", line 340, in loads
>     raise TomlDecodeError("Unbalanced quotes", original, i)
> toml.decoder.TomlDecodeError: Unbalanced quotes (line 39 column 24 char 1554)
> ```
> 
> This is my current config so far... did I miss anything?
> 
> ```
> [SolaxX3RS485]
> poll_period = 10 # seconds
> timeout = 1 # seconds
> baud = 9600
> parity = 'N'
> stopbits = 1
> ports = ["/dev/ttyUSB0]
> ```


O...
